[project]
title = "StrictDoc Documentation"
html_assets_strictdoc_dir = "assets"

features = [
  # Stable features.
  "TABLE_SCREEN",
  "TRACEABILITY_SCREEN",
  "DEEP_TRACEABILITY_SCREEN",
  "PROJECT_STATISTICS_SCREEN",

  # Stable features but not used by StrictDoc.
  # "MATHJAX"

  # Experimental features are disabled when published to GitHub pages.
  # "REQIF",
  # "STANDALONE_DOCUMENT_SCREEN",
  # "REQUIREMENTS_COVERAGE_SCREEN",
  # "REQUIREMENT_TO_SOURCE_TRACEABILITY",
  "HTML2PDF",
]
