name: "StrictDoc - End-to-end tests"

on:
  pull_request:
    branches: [ "**" ]

    # UI tests take 10+ minutes and will continue to grow.
    # Reducing the trigger to only changes in the Web frontend-related code.
    paths:
      - 'strictdoc/export/html/**'
      - 'strictdoc/server/**'
      - 'tests/end2end/**'

jobs:
  tests_end2end_macos:
    name: E2E - macOS
    runs-on: macOS-latest

    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install Invoke
      run: |
        pip install invoke

    - name: Install dependencies
      run: |
        invoke setup-development-deps

    - name: Run end-to-end tasks
      run: |
        invoke test-end2end --long-timeouts

  tests_end2end_linux:
    name: E2E - Linux
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install Invoke
      run: |
        pip install invoke

    - name: Install dependencies
      run: |
        invoke setup-development-deps

    - name: Run end-to-end tasks
      run: |
        invoke test-end2end --long-timeouts

  build:
    name: E2E - Windows
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install Invoke and Tox
      run: |
        pip install invoke tox

    - name: Run end-to-end tasks
      run: |
        invoke test-end2end --long-timeouts
