name: "StrictDoc - End-to-end tests"

on:
  pull_request:
    branches: [ "**" ]

    # UI tests take 10+ minutes and will continue to grow.
    # Reducing the trigger to only changes in the Web frontend-related code.
    paths:
      - 'strictdoc/export/html/**'
      - 'strictdoc/server/**'
      - 'tests/end2end/**'

jobs:
  tests_end2end_macos:
    name: E2E - macOS
    runs-on: macos-13

    strategy:
      matrix:
        shard: [
          "1/4", "2/4",
          "3/4", "4/4",
        ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install minimal Python packages
      run: |
        pip install -r requirements.bootstrap.txt

    - name: Run end-to-end tasks
      run: |
        invoke test-end2end --long-timeouts --shard=${{ matrix.shard }} --exit-first --headless

  tests_end2end_linux:
    name: E2E - Linux
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install minimal Python packages
      run: |
        pip install -r requirements.bootstrap.txt

    - name: Run end-to-end tasks
      run: |
        invoke test-end2end --long-timeouts --exit-first --headless

  build:
    name: E2E - Windows
    runs-on: windows-latest

    strategy:
      matrix:
        shard: [
          "1/4", "2/4",
          "3/4", "4/4",
        ]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install minimal Python packages
      run: |
        pip install -r requirements.bootstrap.txt

    - name: "Windows specific: Install StrictDoc's dependencies"
      run: |
        python developer/pip_install_strictdoc_deps.py

    - name: "Windows specific: Install Check dependencies (everything for test)"
      run: |
        pip install -r requirements.check.txt

    - name: Run end-to-end tasks
      run: |
        invoke test-end2end --long-timeouts --exit-first --shard=${{ matrix.shard }} --headless
