---
name: Periodic Integration Test
on:
  schedule:
    - cron: "00 00 * * *"
  pull_request:
    branches: [ "**" ]

jobs:
  periodic_integration_test:
    name: Periodic integration test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          # python-version: '3.x'
          python-version: '3.10'

      - name: Install release task dependencies
        run: |
          pip install --upgrade pip setuptools invoke

      - name: Build and test locally
        run: |
          invoke release-local

      - name: Build and test using PyInstaller
        run: |
          invoke release-pyinstaller
          invoke test-integration --strictdoc /tmp/strictdoc/strictdoc/strictdoc
