---
name: StrictDoc - Periodic release test
on:
  schedule:
    - cron: "00 00 * * *"

  pull_request:
    branches: [ "**" ]

jobs:
  periodic_release_test_linux:
    name: PRT â€“ Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Invoke and Tox
        run: |
          pip install invoke tox

      - name: Build and test locally
        run: |
          pip install strictdoc --pre

      - name: Integration tests against the StrictDoc Pip package
        run: |
          invoke test-integration --strictdoc `which strictdoc`
