name: StrictDoc Python Package Release

on:
  release:
    types: [created]
  # pull_request:
  #   branches: [ "**" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install release task dependencies
      run: |
        pip install --upgrade pip setuptools twine invoke

    - name: Build and test locally
      run: |
        invoke release-local

    - name: Build and publish
      run: |
        invoke release --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
