name: StrictDoc Python Package Release

on: workflow_dispatch
  # FIXME: Uncomment this when the right workflow is figured out.
  # release:
  #   types: [created]
  # pull_request:
  #   branches: [ "**" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install minimal Python packages
      run: |
        pip install -r requirements.bootstrap.txt

    - name: Build and test locally
      run: |
        invoke release-local

    - name: Build and publish
      run: |
        invoke release --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
